---
tags:
- name: quotes
paths:
  "/ticker":
    x-swagger-router-controller: tickers-controller
    get:
      operationId: ticker
      summary: Retrievs quote for a particular ticker
      description: "Retrievs a quote for a particular ticker\ne.g. AAPL -> { price: 100 }"
      tags:
      - quotes
      responses:
        '200':
          description: Success
          schema:
            x-oad-type: object
            type: object
            title: ticker
            description: The quote for the ticker
            properties:
              price:
                x-oad-type: string
                type: string
          x-oad-type: response
      parameters:
      - name: name
        in: query
        description: Ticker name
        required: true
        type: string
        x-oad-type: parameter
    x-oad-type: operation
  "/tickers":
    get:
      operationId: tickers
      summary: Gets the list of tickers for the current user
      description: Retrieved from assets.json
      tags:
      - quotes
      responses:
        '200':
          description: Success
          schema:
            x-oad-type: array
            type: array
            title: List of tickers
            description: The string list of tickers for the current user
            items:
              x-oad-type: string
              type: string
          x-oad-type: response
    x-oad-type: operation
info:
  title: stocks-watch
  version: '1.0'
basePath: "/"
schemes:
- http
consumes:
- application/json
produces:
- application/json
swagger: '2.0'
